on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Check code
      run: pnpm test
